<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanFilter</name>
   <tag></tag>
   <elementGuidId>54d6f870-4348-4c80-8edb-928e2ce6212a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.filter-bar-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/main/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-bar-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FilterHargaKisaran Harga per MalamResetAreaArea di JakartaResetSetiabudi  (373 properti)Jatinegara  (355 properti)Tanah Abang  (339 properti)Pancoran  (331 properti)Cipinang Besar Selatan  (266 properti)Menteng  (261 properti)Cempaka Putih  (247 properti)Thamrin  (242 properti)Penjaringan  (229 properti)Grogol Petamburan  (219 properti)Kebayoran Baru  (217 properti)Pademangan  (195 properti)Cilandak  (192 properti)Cengkareng  (189 properti)Taman Sari  (184 properti)Pasar Minggu  (182 properti)Kebayoran Lama  (175 properti)Tebet  (175 properti)Sawah Besar  (168 properti)Kembangan  (166 properti)Cikini  (165 properti)Kelapa Gading  (153 properti)Karet Kuningan  (148 properti)Pluit  (136 properti)Tanjung Duren Selatan  (133 properti)Mampang Prapatan  (123 properti)Kemayoran  (120 properti)Senen  (120 properti)Tanjung Priok  (113 properti)Pulau Seribu  (109 properti)Pulo Gadung  (106 properti)Mangga Besar  (101 properti)Kebon Melati  (99 properti)Cilandak Barat  (99 properti)Kemang  (96 properti)Kembangan Selatan  (91 properti)Gambir  (82 properti)Sudirman  (79 properti)Pademangan Timur  (79 properti)Menteng Dalam  (77 properti)Ancol  (75 properti)Fatmawati  (73 properti)Kelapa Gading Barat  (72 properti)Kebon Jeruk  (72 properti)Bangka  (70 properti)Kasablanka  (69 properti)Gatot Subroto  (68 properti)Hayam Wuruk  (67 properti)Duri Kosambi  (66 properti)Pegangsaan Dua  (64 properti)Palmerah  (63 properti)Rawa Buaya  (62 properti)Gajah Mada  (61 properti)Kebon Kacang  (60 properti)Kepulauan Seribu Selatan  (59 properti)Karet Tengsin  (58 properti)Kebagusan  (55 properti)Pesanggrahan  (54 properti)Gunung Sahari Utara  (53 properti)TB Simatupang  (53 properti)Cakung  (53 properti)Bendungan Hilir  (52 properti)Cawang  (52 properti)Blok M  (52 properti)Mangga Dua  (51 properti)Kepulauan Seribu Utara  (50 properti)Sunter Agung  (49 properti)Kamal Muara  (48 properti)Kayu Putih  (47 properti)Pasar Baru  (47 properti)Grogol Utara  (44 properti)Meruya Utara  (43 properti)Melawai  (43 properti)Kebon Sirih  (42 properti)Pulo Gebang  (42 properti)Kalideres  (42 properti)Gelora  (42 properti)Pulau Tidung  (41 properti)Cipete Selatan  (40 properti)Mangga Dua Selatan  (40 properti)Kalibata  (39 properti)Pulau Pramuka  (38 properti)Pulau Panggang  (38 properti)Pademangan Barat  (38 properti)Cipete Utara  (38 properti)Tendean  (37 properti)Harmoni  (36 properti)Pondok Indah  (36 properti)Cipulir  (35 properti)Kramat Jati  (34 properti)Tanjung Duren Utara  (33 properti)Bintaro  (33 properti)Kramat Pela  (33 properti)Cipinang Besar Utara  (32 properti)Kampung Bali  (31 properti)Pusat Kota Tangerang  (30 properti)Matraman  (30 properti)Gondangdia  (30 properti)Senayan  (30 properti)Benda  (29 properti)Duren Sawit  (29 properti)Rawasari  (29 properti)Glodok  (29 properti)Maphar  (29 properti)Kuningan Timur  (28 properti)Gandaria Utara  (28 properti)Cipinang Cempedak  (27 properti)Tambora  (27 properti)Duren Tiga  (27 properti)Pejaten Barat  (27 properti)Ragunan  (26 properti)Sunter Jaya  (25 properti)Jagakarsa  (24 properti)Jati Padang  (24 properti)Pinangsia  (24 properti)Pondok Pinang  (24 properti)Cengkareng Timur  (24 properti)Pela Mampang  (24 properti)Lebak Bulus  (23 properti)Rawa Barat  (23 properti)Kebon Kelapa  (22 properti)Pejaten Timur  (22 properti)Karet  (22 properti)Tebet Timur  (22 properti)Karet Semanggi  (22 properti)Keagungan  (21 properti)Sudirman Central Business District (SCBD)  (21 properti)Srengseng  (21 properti)Cilandak Timur  (20 properti)Kedoya Selatan  (19 properti)Kemanggisan  (19 properti)Makasar  (19 properti)Kelapa Gading Timur  (19 properti)Cideng  (19 properti)Tomang  (19 properti)Koja  (19 properti)Kartini  (19 properti)Grogol  (18 properti)Ciracas  (18 properti)Kenari  (17 properti)Rawamangun  (17 properti)Rawajati  (17 properti)Tangki  (17 properti)Petojo Utara  (16 properti)Gandaria Selatan  (16 properti)Cempaka Putih Timur  (16 properti)Kebayoran Lama Utara  (15 properti)Kebon Kosong  (15 properti)Tegal Alur  (15 properti)Gunung  (14 properti)Pondok Bambu  (14 properti)Karang Anyar  (14 properti)Kwitang  (14 properti)Paseban  (14 properti)Kebon Baru  (14 properti)Pulau Pari  (13 properti)Pejagalan  (13 properti)Cipayung  (12 properti)Pasar Rebo  (12 properti)Kebon Pala  (12 properti)Kampung Melayu  (12 properti)Pulau Kelapa  (12 properti)Grogol Selatan  (12 properti)Kebayoran Lama Selatan  (11 properti)Jembatan Besi  (11 properti)Kuningan Barat  (11 properti)Jelambar  (10 properti)Slipi  (10 properti)Krukut  (10 properti)Johar Baru  (10 properti)Petogogan  (10 properti)Cengkareng Barat  (10 properti)Manggarai Selatan  (9 properti)Cilincing  (9 properti)Pasar Manggis  (9 properti)Pekojan  (9 properti)Pisangan Timur  (9 properti)Pulau Harapan  (8 properti)Bidara Cina  (8 properti)Kapuk  (7 properti)Tanah Tinggi  (7 properti)Gunung Sahari Selatan  (7 properti)Bali Mester  (7 properti)Petamburan  (7 properti)Jati Pulo  (7 properti)Pegangsaan  (7 properti)Kota Bambu Utara  (7 properti)Pegadungan  (7 properti)Jati  (7 properti)Pondok Labu  (7 properti)Tebet Barat  (6 properti)Kelapa Dua  (6 properti)Klender  (6 properti)Tugu Utara  (6 properti)Duri Kepa  (6 properti)Kota Bambu Selatan  (6 properti)Roa Malaka  (6 properti)Petukangan Selatan  (6 properti)Cempaka Putih Barat  (6 properti)Cibubur  (5 properti)Kapuk Muara  (5 properti)Pondok Kelapa  (5 properti)Selong  (5 properti)Menteng Atas  (5 properti)Tegal Parang  (5 properti)Wijaya Kusuma  (5 properti)Joglo  (5 properti)Kedoya Utara  (5 properti)Susukan  (4 properti)Meruya Selatan  (4 properti)Srengseng Sawah  (4 properti)Kebon Bawang  (4 properti)Tugu Selatan  (4 properti)Kramat  (4 properti)Pulo  (4 properti)Tanjung Barat  (4 properti)Gedong  (4 properti)Pisangan Baru  (4 properti)Petojo Selatan  (3 properti)Semper Barat  (3 properti)Pajang  (3 properti)Sukapura  (3 properti)Belendung  (3 properti)Jati Murni  (3 properti)Lenteng Agung  (3 properti)Jurumudi Baru  (3 properti)Utan Kayu Selatan  (3 properti)Sukabumi Utara  (3 properti)Kamal  (3 properti)Ciganjur  (3 properti)Jelambar Baru  (3 properti)Kembangan Utara  (3 properti)Setu  (2 properti)Cililitan  (2 properti)Karang Mulya  (2 properti)Cikoko  (2 properti)Johar Baru  (2 properti)Ceger  (2 properti)Pondok Kopi  (2 properti)Lubang Buaya  (2 properti)Guntur  (2 properti)Rambutan  (2 properti)Duri Pulo  (2 properti)Harapan Mulya  (2 properti)Dukuh  (2 properti)Pinang Ranti  (2 properti)Cakung Timur  (2 properti)Pulau Ayer  (2 properti)Kalibaru  (2 properti)Koja Selatan  (2 properti)Pal Meriam  (2 properti)Cilangkap  (2 properti)Kalisari  (1 properti)Rempoa  (1 properti)Utan Kayu Utara  (1 properti)Pondok Ranggon  (1 properti)Sungai Bambu  (1 properti)Sumur Batu  (1 properti)Kayu Manis  (1 properti)Semanan  (1 properti)Rawa Badak Utara  (1 properti)Jatisampurna  (1 properti)Cempaka Baru  (1 properti)Pulau Macan  (1 properti)Cipinang  (1 properti)Duri Selatan  (1 properti)Galur  (1 properti)Ciputat  (1 properti)Kedaung Kali Angke  (1 properti)Koja Utara  (1 properti)Pengadegan  (1 properti)Bungur  (1 properti)Batu Ampar  (1 properti)Permata Hijau  (1 properti)Jatikarya  (1 properti)Pulau Bidadari  (1 properti)Rawa Terate  (1 properti)Margonda  (1 properti)Pulau Bira  (1 properti)Halim Perdanakusuma  (1 properti)Rawa Badak Selatan  (1 properti)Petukangan Utara  (1 properti)Jati Ranggon  (1 properti)Papanggo  (1 properti)Cipedak  (1 properti)Lagoa  (1 properti)Cipinang Muara  (1 properti)4 bintangBintang HotelReset  (325 properti)  (573 properti)  (2.882 properti)  (955 properti)  (417 properti)Unrated  (489 properti)Filter LainnyaBenefitSarapan Gratis Pembatalan Gratis Deals Metode PembayaranBayar di Hotel FasilitasInDOnesia CAREtiket CLEANKolam RenangWifiParkirRestoranResepsionis 24 JamSpaLiftACPusat KebugaranAntar Jemput BandaraFasilitas RapatAkses Kursi RodaFasilitas AnakFasilitas Kamar Wifi  Bak Mandi  Pembuat Kopi &amp; Teh  Pengering Rambut  Balkon  Dapur  Setrika  TV  Mesin Cuci  Kamar Terhubung Tipe PropertiApartment  (3.122 properti)Hotel  (1.627 properti)Guest House  (515 properti)Hostel  (117 properti)Hostal  (81 properti)Aparthotel  (36 properti)Vacation Home  (23 properti)Resort  (18 properti)Properti  (15 properti)House  (14 properti)Homestay  (14 properti)Capsule Hotel  (14 properti)Residence  (10 properti)Villa  (9 properti)Bed &amp; Breakfast  (6 properti)Motel  (4 properti)Kos  (2 properti)Condo  (2 properti)Bungalow  (1 properti)Cottage  (1 properti)Lainnya  (1 properti)Hotel Bersejarah  (1 properti)Holiday Park  (1 properti)Townhouse  (1 properti)Pension  (1 properti)Love Hotel  (1 properti)Inn  (1 properti)Resort Villa  (1 properti)Bumi Perkemahan  (1 properti)Rating Hotel5 (Fantastis) 4+ (Bagus) 3+ (Oke) Jaringan HotelIndependent  (3.426 properti)Travelio  (1.362 properti)RedDoorz  (324 properti)OYO  (196 properti)Zuzu Hospitality Solution  (68 properti)Zenrooms  (54 properti)Accor Hotels  (34 properti)Archipelago Hotels &amp; Resorts  (23 properti)Santika Indonesia Hotels &amp; Resorts  (22 properti)Marriott International  (12 properti)Tauzia Hotel Management  (11 properti)Swiss-Belhotel International  (9 properti)Waringin Hospitality  (9 properti)MPHG   (9 properti)Mamirooms  (7 properti)The Ascott Limited  (6 properti)Intiwhiz International  (5 properti)d'Prima Hotel  (5 properti)Horison Hotels Group  (4 properti)homes local agencies  (4 properti)Menteng Group  (4 properti)Best Western Indonesia  (4 properti)Hyatt Hotels  (3 properti)Omega Hotel Management  (3 properti)Panorama Hotel Management (PHM Hospitality)  (3 properti)New Hotels  (3 properti)LOUVRE HOTELS  (2 properti)Ace Hotel  (2 properti)Hilton  (2 properti)Kagum Hotels  (2 properti)Fraser Hospitality  (2 properti)Oakwood Worldwide  (2 properti)Dafam Hotels  (2 properti)ZHM Hotels  (1 properti)Topotel  (1 properti)him hospitality  (1 properti)Four Seasons  (1 properti)SAHID HOTELS  (1 properti)Royal Hotels  (1 properti)LIFESTYLE RETREATS  (1 properti)Artotel  (1 properti)Melia  (1 properti)Red Planet  (1 properti)MELAWAI HOTEL  (1 properti)Kempinski Hotels &amp; Resorts  (1 properti)Parador Hotel Management  (1 properti)Wyndham  (1 properti)Shangri-La Hotels and Resorts  (1 properti)Millennium Hotels &amp; Resorts  (1 properti)choice hotels  (1 properti)ResetTerapkan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[1]/div[@class=&quot;hotel-search-list&quot;]/div[@class=&quot;header-search-wrapper&quot;]/div[@class=&quot;filter-bar&quot;]/div[@class=&quot;container flex&quot;]/div[@class=&quot;filter-bar-content&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div/div[2]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
