<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ATMBersama</name>
   <tag></tag>
   <elementGuidId>5dff547a-4e7b-4391-a5b8-fada3b03c9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div[2]/div[2]/div/div/div[2]/div[7]/div/a/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/payment-asset/2020/10/20/048a70c1-a872-4582-afc8-316ecb4f37b6-1603172557892-2da4325d3806bd7892ec1b9ddc4304d7.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tix-ui-fadeIn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;content layout&quot;]/div[@class=&quot;main-wrap&quot;]/div[@class=&quot;landing-page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;payment-list&quot;]/div[2]/div[@class=&quot;payment-methods-list&quot;]/div[@class=&quot;card payment-group white&quot;]/a[1]/div[@class=&quot;payment-method-item&quot;]/div[@class=&quot;method-type-name&quot;]/div[@class=&quot;method-type-logo&quot;]/div[@class=&quot;logo-item&quot;]/img[@class=&quot;tix-ui-fadeIn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div[2]/div/div/div[2]/div[7]/div/a/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/payment-asset/2020/10/20/048a70c1-a872-4582-afc8-316ecb4f37b6-1603172557892-2da4325d3806bd7892ec1b9ddc4304d7.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/a/div/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
